// Données de démonstration pour tester sans backend

export const mockUser = {
  id: 1,
  first_name: 'Admin',
  last_name: 'Demo',
  email: 'admin@demo-ci.com',
  employee_code: 'ADM-001',
  position: 'Administrateur',
  company: {
    name: 'Entreprise Demo CI',
  },
  site: {
    name: 'Bureau Cocody',
  },
}

export const mockStats = {
  present_count: 156,
  late_count: 12,
  absent_count: 8,
  total_employees: 176,
  present_percentage: 88.6,
}

export const mockWeekStats = [
  { day: 'Lundi', day_fr: 'Lun', present_count: 165, late_count: 8, total_hours: 1320 },
  { day: 'Mardi', day_fr: 'Mar', present_count: 170, late_count: 5, total_hours: 1360 },
  { day: 'Mercredi', day_fr: 'Mer', present_count: 168, late_count: 7, total_hours: 1344 },
  { day: 'Jeudi', day_fr: 'Jeu', present_count: 172, late_count: 3, total_hours: 1376 },
  { day: 'Vendredi', day_fr: 'Ven', present_count: 156, late_count: 12, total_hours: 1248 },
  { day: 'Samedi', day_fr: 'Sam', present_count: 145, late_count: 6, total_hours: 725 },
  { day: 'Dimanche', day_fr: 'Dim', present_count: 0, late_count: 0, total_hours: 0 },
]

export const mockEmployees = [
  {
    id: 1,
    employee_code: 'EMP-001',
    first_name: 'Kouassi',
    last_name: 'Ama',
    email: 'kouassi.ama@demo-ci.com',
    phone: '+225 05 01 01 01 01',
    position: 'Vendeur',
    contract_type: 'CDI',
    is_active: true,
    site: { name: 'Boutique Bingerville' },
    department: { name: 'Commercial' },
  },
  {
    id: 2,
    employee_code: 'EMP-002',
    first_name: 'Yao',
    last_name: 'Marie',
    email: 'yao.marie@demo-ci.com',
    phone: '+225 05 02 02 02 02',
    position: 'Caissière',
    contract_type: 'CDI',
    is_active: true,
    site: { name: 'Boutique Bingerville' },
    department: { name: 'Commercial' },
  },
  {
    id: 3,
    employee_code: 'EMP-003',
    first_name: 'Bamba',
    last_name: 'Koné',
    email: 'bamba.kone@demo-ci.com',
    phone: '+225 05 03 03 03 03',
    position: 'Magasinier',
    contract_type: 'CDI',
    is_active: true,
    site: { name: 'Entrepôt Yopougon' },
    department: { name: 'Logistique' },
  },
  {
    id: 4,
    employee_code: 'EMP-004',
    first_name: 'Traoré',
    last_name: 'Salif',
    email: 'traore.salif@demo-ci.com',
    phone: '+225 05 04 04 04 04',
    position: 'Ouvrier',
    contract_type: 'CDI',
    is_active: true,
    site: { name: 'Entrepôt Yopougon' },
    department: { name: 'Production' },
  },
  {
    id: 5,
    employee_code: 'EMP-005',
    first_name: 'Koné',
    last_name: 'Fanta',
    email: 'kone.fanta@demo-ci.com',
    phone: '+225 05 05 05 05 05',
    position: 'Vendeuse',
    contract_type: 'CDI',
    is_active: true,
    site: { name: 'Boutique Bingerville' },
    department: { name: 'Commercial' },
  },
  {
    id: 6,
    employee_code: 'ADM-001',
    first_name: 'Admin',
    last_name: 'Demo',
    email: 'admin@demo-ci.com',
    phone: '+225 02 02 02 02 02',
    position: 'Administrateur',
    contract_type: 'CDI',
    is_active: true,
    site: { name: 'Bureau Cocody' },
    department: { name: 'Administration' },
  },
]

export const mockAttendances = [
  {
    id: 1,
    date: '2025-12-10',
    user: { first_name: 'Kouassi', last_name: 'Ama', employee_code: 'EMP-001' },
    clock_in: '2025-12-10T08:05:00Z',
    clock_out: '2025-12-10T17:10:00Z',
    total_minutes: 485,
    work_minutes: 425,
    late_minutes: 5,
    status: 'LATE',
    site: { name: 'Bingerville' },
  },
  {
    id: 2,
    date: '2025-12-10',
    user: { first_name: 'Yao', last_name: 'Marie', employee_code: 'EMP-002' },
    clock_in: '2025-12-10T07:55:00Z',
    clock_out: '2025-12-10T17:00:00Z',
    total_minutes: 485,
    work_minutes: 425,
    late_minutes: 0,
    status: 'PRESENT',
    site: { name: 'Bingerville' },
  },
  {
    id: 3,
    date: '2025-12-10',
    user: { first_name: 'Bamba', last_name: 'Koné', employee_code: 'EMP-003' },
    clock_in: null,
    clock_out: null,
    status: 'ABSENT',
    site: { name: 'Yopougon' },
  },
]

